services:
  # Images Project
  biblioteca:
    container_name: biblioteca_virtual
    build:
      dockerfile: ops/Dockerfile
    restart: unless-stopped
    ports:
      - "8021:8021"
    working_dir: /var/www/html/bibliotecaVirtual
    volumes:
      - ./projects/bibliotecaVirtual:/var/www/html/bibliotecaVirtual
    networks:
      - biblioteca

  # db mysql
  mysql:
    container_name: biblioteca-mysql
    image: mysql:8.0.32
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: biblioteca
      MYSQL_ROOT_PASSWORD: biblioteca
      MYSQL_PASSWORD: biblioteca
      MYSQL_USER: biblioteca
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --sql-mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION" --skip-ssl
    ports:
      - "3368:3306"
    networks:
      - biblioteca

networks:
  biblioteca:
    driver: bridge
